### ISSUE TITLE
FE-C ANT+ profile

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#33]
It would be nice to have trainers driven by app..
Slope/wind messages should be send to the trainer (to set proper resistance), reported power should be used to compute video speed (or.. reported distance.. but what will happen if requested slope is bigger than allowed??)
CdA and Crr should be added to the config.. and to the "general" calculations.

**Comment by ibooij** [comment]
For sure we need to do this.

I'm thinking of buying an FE-C ANT+ trainer, so that will make testing a bit easier. 
From what I've been reading, most applications calculate speed from the reported power, which also make sure that we don't need to handle the slope being steeper than what the trainer hardware can handle. Although it would be nice to give the user feedback on the fact that speed is going into "virtual mode". That would be an enhancement.

CdA and Crr are already handled in the Simulation class, https://github.com/ibooij/big-ring/blob/master/mainlib/simulation.cpp, but are constants now. It would be an enhancement to add those, but I would be cautious to add this to the configuration, maybe only in an "advanced" section.

**Comment by ibooij** [comment]
I've been working on this, because I have an ANT+ trainer since last Friday (an Elite Real Turbo Muin B+). In the feature/ant-fe-c-support branch is a first implementation. It works quite nicely.

Calibration is still missing.

Something that sometimes seems to go wrong is that for a ride, the trainer does not seem to be initialized ok. It will than not give the right level of resistance. Perhaps the messages to initialize simulation mode are sent too quickly. I'll have a look at the documentation to see if we can get some better feedback from the trainer before really starting.

**Comment by ibooij** [comment]
Alpha implementation merged in to master in 4e056157c8534f6f4a8f8bb8eebac4b2e987df83.

More testing, with more trainers is needed. Only tested with an Elite Real Turbo Muin B+.
