### ISSUE TITLE
Routes without video

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#37]
Routes without video should be valid (they should be shown in the list)
Starting training without video shouldn't be available (the [Start] button insensitive).
There should be possibility to change video file (location) for routes. Selecting new video shall repaint thumbnails and set [Start] button sensitive.
Assignment route-video should be persistent, opening video should start from "default" location (this is.. route directory or last opened video directory)

**Comment by ibooij** [comment]
Could you explain what the purpose of having routes without an attached video file is? Do you use it for producing new videos? 

I ask this because I would like Big Ring to be as simple as possible to use for a typical user who just want to ride and not be bothered with all kinds of options. This looks, to me, more like "advanced" usage, which should be hidden from most typical users, but probably be available to advanced users.

**Comment by pajakgdynia** [comment]
Main reasons.. Video file name different than expected for control file.
Video in different location where control file. Video on removable disk
(CD/DVD/BR, SD card, ...)
In my opinion matching control and video files in such scenarios is "more
advanced".. It won't be used too often, either.

Yes, I create own RLVs. Some videos are on attachable HDD, some on NAS.
Keeping order with all videos and training results.. Nightmare..

In another app I did terrible solution to allow loading another video. It
can be solved with symbolic link.. but this is too advanced for most people.

**Comment by ibooij** [comment]
For now, I don't think it'll help many users to make this configurable. Closing the issue.
