### ISSUE TITLE
Enable MP4 video format playback

### ISSUE THREAD

**Issue by vladn2012** [ibooij/big-ring#70]
Currently only AVI container is supported, many devices record in MP4 container requiring users to convert to AVI.

**Comment by ibooij** [comment]
I think I'm on to something, using time_base to determine frame numbers. I don't think I'll be able to fix this this week, maybe in the weekend.

**Comment by ibooij** [comment]
I've made some changes in the feature/fix_mp4_support branch. These work, but it's still quite rough. Especially when starting the video stutters a lot.

It doesn't work with h265 encoding unfortunately.

**Comment by vladn2012** [comment]
What MP4 video did you test, original US_DeerCreek (4GB) ?

**Comment by ibooij** [comment]
Yes, US_DeerCreek.mp4 with H264 encoding, so the 4GB one.

**Comment by ibooij** [comment]
There's an interesting thing in the gpx file: The first few points in the gpx are very close to each other, in distance, which makes the the number of frames per meter very high. Because of this, the program has to decode a lot of frames in short time, which causes stuttering.

Still, we should handle this a bit better..

**Comment by ibooij** [comment]
BETA support for mp4 (no H265 yet) added in master in commit 080db3d0605cd9ffff49c8e9b18484d4542e9c1d
